##########
CC = gcc
INCLUDE_DIR = includes
INCLUDE_OPT = -I $(INCLUDE_DIR)
CCOPTS = -c $(INCLUDE_OPT)
LINKOPTS = -lpthread -lm

ALL = all
MKDIR_OBJS = mkdir_objs
MKDIR_LIBS = mkdir_libs
ERASE = erase
CLEAN = clean

LIB_DIR = libs
LIBOPTS = -L./$(LIB_DIR)
DDOS_LIB_NAME = ddos
BASE_LIB_NAME = base
DDOS_LIB_A = $(LIB_DIR)/lib$(DDOS_LIB_NAME).a
BASE_LIB_A = $(LIB_DIR)/lib$(BASE_LIB_NAME).a
TARGET = attack.out

SRC_DIR = srcs
BASE_DIR = base
DDOS_DIR = ddos
OBJ_DIR = objs

#########

MAKE_IPV4_C = $(SRC_DIR)/$(BASE_DIR)/make_ipv4.c
MAKE_TCP_C  = $(SRC_DIR)/$(BASE_DIR)/make_tcp.c
MAKE_HTTP_C  = $(SRC_DIR)/$(BASE_DIR)/make_http.c
RECEIVER_C = $(SRC_DIR)/$(BASE_DIR)/receiver.c
SUBNET_MASK_C = $(SRC_DIR)/$(BASE_DIR)/subnet_mask.c
TIME_CHECK_C = $(SRC_DIR)/$(BASE_DIR)/time_check.c

CONN_FLOOD_C = $(SRC_DIR)/$(DDOS_DIR)/conn_flood.c
GET_FLOOD_C = $(SRC_DIR)/$(DDOS_DIR)/get_flood.c
SYN_FLOOD_C = $(SRC_DIR)/$(DDOS_DIR)/syn_flood.c
UDP_FLOOD_C = $(SRC_DIR)/$(DDOS_DIR)/udp_flood.c
ICMP_FLOOD_C = $(SRC_DIR)/$(DDOS_DIR)/icmp_flood.c
HASH_DOS_C = $(SRC_DIR)/$(DDOS_DIR)/hash_dos.c
HEADER_BUFFERING_C = $(SRC_DIR)/$(DDOS_DIR)/header_buffering.c
BODY_BUFFERING_C = $(SRC_DIR)/$(DDOS_DIR)/body_buffering.c
RESPONSE_BUFFERING_C = $(SRC_DIR)/$(DDOS_DIR)/response_buffering.c

MAIN_C = $(SRC_DIR)/main.c

#########

MAKE_IPV4_O = $(OBJ_DIR)/make_ipv4.o
MAKE_TCP_O  = $(OBJ_DIR)/make_tcp.o
MAKE_HTTP_O  = $(OBJ_DIR)/make_http.o
RECEIVER_O = $(OBJ_DIR)/receiver.o
SUBNET_MASK_O = $(OBJ_DIR)/subnet_mask.o
TIME_CHECK_O = $(OBJ_DIR)/time_check.o

CONN_FLOOD_O = $(OBJ_DIR)/conn_flood.o
GET_FLOOD_O = $(OBJ_DIR)/get_flood.o
SYN_FLOOD_O = $(OBJ_DIR)/syn_flood.o
UDP_FLOOD_O = $(OBJ_DIR)/udp_flood.o
ICMP_FLOOD_O = $(OBJ_DIR)/icmp_flood.o
HASH_DOS_O = $(OBJ_DIR)/hash_dos.o
HEADER_BUFFERING_O = $(OBJ_DIR)/header_buffering.o
BODY_BUFFERING_O = $(OBJ_DIR)/body_buffering.o
RESPONSE_BUFFERING_O = $(OBJ_DIR)/response_buffering.o

MAIN_O = $(OBJ_DIR)/main.o

#########

.SUFFIXES : .c.h.o.a.out
.PHONY: $(ALL) $(MKDIR_OBJ) $(CLEAN)

$(ALL): $(TARGET)

$(DDOS_LIB_A): $(MKDIR_LIBS) $(GET_FLOOD_O) $(CONN_FLOOD_O) $(SYN_FLOOD_O) $(UDP_FLOOD_O) $(ICMP_FLOOD_O) $(HASH_DOS_O) $(HEADER_BUFFERING_O) $(RESPONSE_BUFFERING_O) $(BODY_BUFFERING_O)
	ar -rc $(DDOS_LIB_A) $(GET_FLOOD_O) $(CONN_FLOOD_O) $(SYN_FLOOD_O) $(UDP_FLOOD_O) $(ICMP_FLOOD_O) $(HASH_DOS_O) $(HEADER_BUFFERING_O) $(RESPONSE_BUFFERING_O) $(BODY_BUFFERING_O)
	ranlib $(DDOS_LIB_A)

$(BASE_LIB_A): $(MKDIR_OBJ) $(MKDIR_LIBS) $(MAKE_IPV4_O) $(MAKE_TCP_O) $(RECEIVER_O) $(SUBNET_MASK_O) $(TIME_CHECK_O)
	ar -rc $(BASE_LIB_A) $(MAKE_IPV4_O) $(MAKE_TCP_O) $(RECEIVER_O) $(SUBNET_MASK_O) $(TIME_CHECK_O)
	ranlib $(BASE_LIB_A)

$(TARGET): $(LIB) $(MAIN_O)
	gcc $(INCLUDE_OPT) $(MAIN_O) $(LIBOPTS) -l$(DDOS_LIB_NAME) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(TARGET)

$(MKDIR_OBJS):
	mkdir -p objs

$(MKDIR_LIBS):
	mkdir -p libs

$(CLEAN):
	rm -f $(OBJ_DIR)/*.o $(DDOS_LIB_A) $(BASE_LIB_A) attack.out

$(MAIN_O): $(DDOS_LIB_A) $(MAIN_C)
	$(CC) $(CCOPTS) $(MAIN_C) $(LINKOPTS) -o $(MAIN_O)

$(MAKE_IPV4_O): $(MAKE_IPV4_C)
	$(CC) $(CCOPTS) $(MAKE_IPV4_C) $(LINKOPTS) -o $(MAKE_IPV4_O)

$(MAKE_TCP_O): $(MAKE_TCP_C)
	$(CC) $(CCOPTS) $(MAKE_TCP_C) $(LINKOPTS) -o $(MAKE_TCP_O)

$(RECEIVER_O): $(RECEIVER_C)
	$(CC) $(CCOPTS) $(RECEIVER_C) $(LINKOPTS) -o $(RECEIVER_O)

$(SUBNET_MASK_O): $(SUBNET_MASK_C)
	$(CC) $(CCOPTS) $(SUBNET_MASK_C) $(LINKOPTS) -o $(SUBNET_MASK_O)

$(TIME_CHECK_O): $(TIME_CHECK_C)
	$(CC) $(CCOPTS) $(TIME_CHECK_C) $(LINKOPTS) -o $(TIME_CHECK_O)

$(GET_FLOOD_O): $(BASE_LIB_A) $(GET_FLOOD_C)
	$(CC) $(CCOPTS) $(GET_FLOOD_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(GET_FLOOD_O)

$(CONN_FLOOD_O): $(BASE_LIB_A) $(CONN_FLOOD_C)
	$(CC) $(CCOPTS) $(CONN_FLOOD_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(CONN_FLOOD_O)

$(SYN_FLOOD_O): $(BASE_LIB_A) $(SYN_FLOOD_C)
	$(CC) $(CCOPTS) $(SYN_FLOOD_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(SYN_FLOOD_O)

$(UDP_FLOOD_O): $(BASE_LIB_A) $(UDP_FLOOD_C)
	$(CC) $(CCOPTS) $(UDP_FLOOD_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(UDP_FLOOD_O)

$(ICMP_FLOOD_O): $(BASE_LIB_A) $(ICMP_FLOOD_C)
	$(CC) $(CCOPTS) $(ICMP_FLOOD_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(ICMP_FLOOD_O)

$(HASH_DOS_O): $(BASE_LIB_A) $(HASH_DOS_C)
	$(CC) $(CCOPTS) $(HASH_DOS_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(HASH_DOS_O)

$(HEADER_BUFFERING_O): $(BASE_LIB_A) $(HEADER_BUFFERING_C)
	$(CC) $(CCOPTS) $(HEADER_BUFFERING_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(HEADER_BUFFERING_O)

$(BODY_BUFFERING_O): $(BASE_LIB_A) $(BODY_BUFFERING_C)
	$(CC) $(CCOPTS) $(BODY_BUFFERING_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(BODY_BUFFERING_O)

$(RESPONSE_BUFFERING_O): $(BASE_LIB_A) $(RESPONSE_BUFFERING_C)
	$(CC) $(CCOPTS) $(RESPONSE_BUFFERING_C) -L./$(LIBOPTS) -l$(BASE_LIB_NAME) $(LINKOPTS) -o $(RESPONSE_BUFFERING_O)
