.TH "includes/base/asm_types.h" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/base/asm_types.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned short \fBumode_t\fP"
.br
.ti -1c
.RI "typedef char \fB__sc\fP"
.br
.ti -1c
.RI "typedef unsigned char \fB__uc\fP"
.br
.ti -1c
.RI "typedef int8_t \fB__s8\fP"
.br
.ti -1c
.RI "typedef uint8_t \fB__u8\fP"
.br
.ti -1c
.RI "typedef int16_t \fB__s16\fP"
.br
.ti -1c
.RI "typedef uint16_t \fB__u16\fP"
.br
.ti -1c
.RI "typedef int32_t \fB__s32\fP"
.br
.ti -1c
.RI "typedef uint32_t \fB__u32\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int16_t \fB__s16\fP"

.PP
Definition at line 17 of file asm_types\&.h\&.
.SS "typedef int32_t \fB__s32\fP"

.PP
Definition at line 20 of file asm_types\&.h\&.
.SS "typedef int8_t \fB__s8\fP"

.PP
Definition at line 14 of file asm_types\&.h\&.
.SS "typedef char \fB__sc\fP"

.PP
Definition at line 11 of file asm_types\&.h\&.
.SS "typedef uint16_t \fB__u16\fP"

.PP
Definition at line 18 of file asm_types\&.h\&.
.SS "typedef uint32_t \fB__u32\fP"

.PP
Definition at line 21 of file asm_types\&.h\&.
.SS "typedef uint8_t \fB__u8\fP"

.PP
Definition at line 15 of file asm_types\&.h\&.
.SS "typedef unsigned char \fB__uc\fP"

.PP
Definition at line 12 of file asm_types\&.h\&.
.SS "typedef unsigned short \fBumode_t\fP"

.PP
Definition at line 4 of file asm_types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
