.TH "includes/ddos/body_buffering.h" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/ddos/body_buffering.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__BODY_BUFFERING_REQUEST_MSG_SIZE__\fP   100"
.br
.RI "http request method message size in body buffering "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbody_buffering_print_usage\fP (void)"
.br
.RI "print body buffering usage "
.ti -1c
.RI "void * \fBgenerate_body_buffering\fP (void *data)"
.br
.RI "body buffering generate thread "
.ti -1c
.RI "void * \fBbody_buffering_time_check\fP (void *data)"
.br
.RI "body buffering time check thread "
.ti -1c
.RI "void \fBbody_buffering_main\fP (char *argv[])"
.br
.RI "body buffering main function "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __BODY_BUFFERING_REQUEST_MSG_SIZE__   100"

.PP
http request method message size in body buffering 
.PP
Definition at line 6 of file body_buffering\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void body_buffering_main (char * argv[])"

.PP
body buffering main function 
.PP
\fBDate:\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 121 of file body_buffering\&.c\&.
.SS "void body_buffering_print_usage (void)"

.PP
print body buffering usage 
.PP
\fBDate:\fP
.RS 4
2021/02/20 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file body_buffering\&.c\&.
.SS "void* body_buffering_time_check (void * data)"

.PP
body buffering time check thread 
.PP
\fBDate:\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 107 of file body_buffering\&.c\&.
.SS "void* generate_body_buffering (void * data)"

.PP
body buffering generate thread 
.PP
\fBDate:\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 36 of file body_buffering\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
