.TH "includes/ddos/hash_dos.h" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/ddos/hash_dos.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhash_dos_print_usage\fP (void)"
.br
.RI "print hash dos usage "
.ti -1c
.RI "void * \fBgenerate_hash_dos\fP (void *data)"
.br
.RI "hash dos generate thread "
.ti -1c
.RI "void * \fBhash_dos_time_check\fP (void *data)"
.br
.RI "hash dos time check thread "
.ti -1c
.RI "void \fBhash_dos_main\fP (char *argv[])"
.br
.RI "hash dos main function "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* generate_hash_dos (void * data)"

.PP
hash dos generate thread 
.PP
\fBDate:\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 35 of file hash_dos\&.c\&.
.SS "void hash_dos_main (char * argv[])"

.PP
hash dos main function 
.PP
\fBDate:\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 116 of file hash_dos\&.c\&.
.SS "void hash_dos_print_usage (void)"

.PP
print hash dos usage 
.PP
\fBDate:\fP
.RS 4
2021/03/15 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file hash_dos\&.c\&.
.SS "void* hash_dos_time_check (void * data)"

.PP
hash dos time check thread 
.PP
\fBDate:\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 102 of file hash_dos\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
