.TH "srcs/ddos/hash_dos.c" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/ddos/hash_dos.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/make_ipv4\&.h'\fP
.br
\fC#include 'base/subnet_mask\&.h'\fP
.br
\fC#include 'base/time_check\&.h'\fP
.br
\fC#include 'ddos/hash_dos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhash_dos_print_usage\fP (void)"
.br
.RI "print hash dos usage "
.ti -1c
.RI "void * \fBgenerate_hash_dos\fP (void *data)"
.br
.RI "hash dos generate thread "
.ti -1c
.RI "void * \fBhash_dos_time_check\fP (void *data)"
.br
.RI "hash dos time check thread "
.ti -1c
.RI "void \fBhash_dos_main\fP (char *argv[])"
.br
.RI "hash dos main function "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBg_num_threads\fP"
.br
.ti -1c
.RI "__u64 \fBg_hash_dos_num_total\fP"
.br
.ti -1c
.RI "__u64 \fBg_hash_dos_num_generated_in_sec\fP"
.br
.ti -1c
.RI "\fBInputArguments\fP \fBg_hash_dos_input\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBg_hash_dos_request_per_sec\fP"
.br
.ti -1c
.RI "\fBMaskingArguments\fP \fBg_hash_dos_now\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBg_hash_dos_mutex\fP = PTHREAD_MUTEX_INITIALIZER"
.br
.ti -1c
.RI "pthread_cond_t \fBg_hash_dos_cond\fP"
.br
.ti -1c
.RI "struct timespec \fBg_hash_dos_before_time\fP"
.br
.ti -1c
.RI "struct timespec \fBg_hash_dos_now_time\fP"
.br
.ti -1c
.RI "char \fBhash_dos_content\fP [1001]"
.br
.ti -1c
.RI "char \fBhash_dos_method\fP [1300]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* generate_hash_dos (void * data)"

.PP
hash dos generate thread 
.PP
\fBDate\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns\fP
.RS 4
void * 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 34 of file hash_dos\&.c\&.
.SS "void hash_dos_main (char * argv[])"

.PP
hash dos main function 
.PP
\fBDate\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 115 of file hash_dos\&.c\&.
.SS "void hash_dos_print_usage (void)"

.PP
print hash dos usage 
.PP
\fBDate\fP
.RS 4
2021/03/15 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 27 of file hash_dos\&.c\&.
.SS "void* hash_dos_time_check (void * data)"

.PP
hash dos time check thread 
.PP
\fBDate\fP
.RS 4
2021/03/15 
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns\fP
.RS 4
void * 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 101 of file hash_dos\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct timespec g_hash_dos_before_time"

.PP
Definition at line 19 of file hash_dos\&.c\&.
.SS "pthread_cond_t g_hash_dos_cond"

.PP
Definition at line 19 of file hash_dos\&.c\&.
.SS "\fBInputArguments\fP g_hash_dos_input"

.PP
Definition at line 13 of file hash_dos\&.c\&.
.SS "pthread_mutex_t g_hash_dos_mutex = PTHREAD_MUTEX_INITIALIZER"

.PP
Definition at line 18 of file hash_dos\&.c\&.
.SS "\fBMaskingArguments\fP g_hash_dos_now"

.PP
Definition at line 16 of file hash_dos\&.c\&.
.SS "struct timespec g_hash_dos_now_time"

.PP
Definition at line 19 of file hash_dos\&.c\&.
.SS "__u64 g_hash_dos_num_generated_in_sec"

.PP
Definition at line 11 of file hash_dos\&.c\&.
.SS "__u64 g_hash_dos_num_total"

.PP
Definition at line 10 of file hash_dos\&.c\&.
.SS "\fB__u32\fP g_hash_dos_request_per_sec"

.PP
Definition at line 14 of file hash_dos\&.c\&.
.SS "int g_num_threads\fC [extern]\fP"

.PP
Definition at line 19 of file main\&.c\&.
.SS "char hash_dos_content[1001]"

.PP
Definition at line 24 of file hash_dos\&.c\&.
.SS "char hash_dos_method[1300]"

.PP
Definition at line 25 of file hash_dos\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
