.TH "srcs/ddos/icmp_flood.c" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/ddos/icmp_flood.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/make_ipv4\&.h'\fP
.br
\fC#include 'base/subnet_mask\&.h'\fP
.br
\fC#include 'base/time_check\&.h'\fP
.br
\fC#include 'ddos/icmp_flood\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBicmp_flood_print_usage\fP (void)"
.br
.RI "print icmp flooding usage "
.ti -1c
.RI "void * \fBgenerate_icmp_flood\fP (void *data)"
.br
.RI "icmp flooding generate thread "
.ti -1c
.RI "void * \fBicmp_flood_time_check\fP (void *data)"
.br
.RI "icmp flooding time check thread "
.ti -1c
.RI "void \fBicmp_flood_main\fP (char *argv[])"
.br
.RI "icmp flooding main function "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBg_num_threads\fP"
.br
.ti -1c
.RI "__u64 \fBg_icmp_num_total\fP"
.br
.ti -1c
.RI "__u64 \fBg_icmp_num_generated_in_sec\fP"
.br
.ti -1c
.RI "\fBInputArguments\fP \fBg_icmp_input\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBg_icmp_request_per_sec\fP"
.br
.ti -1c
.RI "\fBMaskingArguments\fP \fBg_icmp_now\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBg_icmp_mutex\fP = PTHREAD_MUTEX_INITIALIZER"
.br
.ti -1c
.RI "pthread_cond_t \fBg_icmp_cond\fP = PTHREAD_COND_INITIALIZER"
.br
.ti -1c
.RI "struct timespec \fBg_icmp_before_time\fP"
.br
.ti -1c
.RI "struct timespec \fBg_icmp_now_time\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* generate_icmp_flood (void * data)"

.PP
icmp flooding generate thread 
.PP
\fBDate\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns\fP
.RS 4
void * 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 31 of file icmp_flood\&.c\&.
.SS "void icmp_flood_main (char * argv[])"

.PP
icmp flooding main function 
.PP
\fBDate\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 110 of file icmp_flood\&.c\&.
.SS "void icmp_flood_print_usage (void)"

.PP
print icmp flooding usage 
.PP
\fBDate\fP
.RS 4
2021/02/20 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 24 of file icmp_flood\&.c\&.
.SS "void* icmp_flood_time_check (void * data)"

.PP
icmp flooding time check thread 
.PP
\fBDate\fP
.RS 4
2021/02/20 
.RE
.PP
\fBParameters\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns\fP
.RS 4
void * 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 96 of file icmp_flood\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct timespec g_icmp_before_time"

.PP
Definition at line 19 of file icmp_flood\&.c\&.
.SS "pthread_cond_t g_icmp_cond = PTHREAD_COND_INITIALIZER"

.PP
Definition at line 19 of file icmp_flood\&.c\&.
.SS "\fBInputArguments\fP g_icmp_input"

.PP
Definition at line 13 of file icmp_flood\&.c\&.
.SS "pthread_mutex_t g_icmp_mutex = PTHREAD_MUTEX_INITIALIZER"

.PP
Definition at line 18 of file icmp_flood\&.c\&.
.SS "\fBMaskingArguments\fP g_icmp_now"

.PP
Definition at line 16 of file icmp_flood\&.c\&.
.SS "struct timespec g_icmp_now_time"

.PP
Definition at line 19 of file icmp_flood\&.c\&.
.SS "__u64 g_icmp_num_generated_in_sec"

.PP
Definition at line 11 of file icmp_flood\&.c\&.
.SS "__u64 g_icmp_num_total"

.PP
Definition at line 10 of file icmp_flood\&.c\&.
.SS "\fB__u32\fP g_icmp_request_per_sec"

.PP
Definition at line 14 of file icmp_flood\&.c\&.
.SS "int g_num_threads\fC [extern]\fP"

.PP
Definition at line 19 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
