.TH "ip_pair" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_pair
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_replay\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBip1\fP [16]"
.br
.ti -1c
.RI "char \fBip2\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file tcp_replay\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char ip1[16]"

.PP
Definition at line 4 of file tcp_replay\&.h\&.
.SS "char ip2[16]"

.PP
Definition at line 5 of file tcp_replay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
