.TH "includes/main.h" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/main.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_input\fP (void)"
.br
.RI "read stdin g_input to with printing a prompt character('$') "
.ti -1c
.RI "void \fBmake_tokens\fP (void)"
.br
.RI "tokenize(seperator ' ') g_input to g_tokens "
.ti -1c
.RI "\fBbool\fP \fBcheck_options\fP (char *argv[], int argc)"
.br
.RI "read argv[] and handle option (-r, -c, -t, --help), decide program's mode (command mode / prompt mode) "
.ti -1c
.RI "\fBattack_type\fP \fBargv_to_tokens\fP (char *argv[], int argc)"
.br
.RI "in command mode, convert argv to g_tokens "
.ti -1c
.RI "\fBattack_type\fP \fBtype_choose_attack\fP (void)"
.br
.RI "print attack types and read stdin for choosing "
.ti -1c
.RI "void \fBprint_logo\fP (void)"
.br
.RI "print DDoS Util logo "
.ti -1c
.RI "void \fBprint_usage\fP (char *argv[])"
.br
.RI "print man page when --help option or argument error "
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "program's main function "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBattack_type\fP argv_to_tokens (char * argv[], int argc)"

.PP
in command mode, convert argv to g_tokens 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP main's argv 
.br
\fIargc\fP main's argc 
.RE
.PP
\fBReturns:\fP
.RS 4
attack_type 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI1~10\fP correct atack type (attack_type's enum value) 
.br
\fI0\fP NONE (error occured) 
.RE
.PP

.PP
Definition at line 108 of file main\&.c\&.
.SS "\fBbool\fP check_options (char * argv[], int argc)"

.PP
read argv[] and handle option (-r, -c, -t, --help), decide program's mode (command mode / prompt mode) 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP main's argv 
.br
\fIargc\fP main's argc 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI1(true)\fP is command mode 
.br
\fI0(false)\fP is prompt mode 
.RE
.PP

.PP
Definition at line 84 of file main\&.c\&.
.SS "void get_input (void)"

.PP
read stdin g_input to with printing a prompt character('$') 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 63 of file main\&.c\&.
.SS "int main (int argc, char * argv[])"

.PP
program's main function 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP argument vectors 
.br
\fIargc\fP argument count 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP normal exit 
.br
\fI1\fP error 
.RE
.PP

.PP
Definition at line 321 of file main\&.c\&.
.SS "void make_tokens (void)"

.PP
tokenize(seperator ' ') g_input to g_tokens 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 70 of file main\&.c\&.
.SS "void print_logo (void)"

.PP
print DDoS Util logo 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 214 of file main\&.c\&.
.SS "void print_usage (char * argv[])"

.PP
print man page when --help option or argument error 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 273 of file main\&.c\&.
.SS "\fBattack_type\fP type_choose_attack (void)"

.PP
print attack types and read stdin for choosing 
.PP
\fBDate:\fP
.RS 4
2021/04/12 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI1~10\fP correct atack type (attack_type's enum value) 
.br
\fI0\fP NONE (error occured) 
.RE
.PP

.PP
Definition at line 184 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
