.TH "srcs/base/make_tcp.c" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/base/make_tcp.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/make_ipv4\&.h'\fP
.br
\fC#include 'base/make_tcp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct tcphdr \fBprepare_empty_tcp\fP (void)"
.br
.RI "function: get empty tcphdr "
.ti -1c
.RI "struct tcphdr \fBtcp_set_src_port\fP (struct tcphdr tcph, \fB__u16\fP src_port)"
.br
.RI "function: set tcphdr's src port "
.ti -1c
.RI "struct tcphdr \fBtcp_set_dest_port\fP (struct tcphdr tcph, \fB__u16\fP \fBdest_port\fP)"
.br
.RI "function: set tcphdr's src port "
.ti -1c
.RI "struct tcphdr \fBtcp_set_seq\fP (struct tcphdr tcph, \fB__u32\fP seq)"
.br
.ti -1c
.RI "struct tcphdr \fBtcp_set_ack_seq\fP (struct tcphdr tcph, \fB__u32\fP ack_seq)"
.br
.RI "function: set tcphdr's ack sequence "
.ti -1c
.RI "struct tcphdr \fBtcp_set_syn_flag\fP (struct tcphdr tcph)"
.br
.RI "function: set tcphdr's syn flag as 1 "
.ti -1c
.RI "struct tcphdr \fBtcp_set_ack_flag\fP (struct tcphdr tcph)"
.br
.ti -1c
.RI "struct tcphdr \fBtcp_set_psh_flag\fP (struct tcphdr tcph)"
.br
.RI "function: set tcphdr's psh flag as 1 "
.ti -1c
.RI "struct tcphdr \fBtcp_set_window_size\fP (struct tcphdr tcph, \fB__u16\fP window_size)"
.br
.RI "function: set tcphdr's window size "
.ti -1c
.RI "struct tcphdr \fBtcp_get_checksum\fP (struct iphdr ipv4h, struct tcphdr tcph, void *data, int datasize)"
.br
.RI "function: tcphdr checksum value calculate with iphdr, data "
.ti -1c
.RI "int \fBtcp_make_connection\fP (\fB__u32\fP src_ip, \fB__u32\fP dest_ip, int *src_port_copy, int \fBdest_port\fP, int *seq_copy, int *ack_copy, \fB__u16\fP window_size)"
.br
.RI "function: make tcp connection (3-way handshake, 1\&. send SYN, 2\&. receive SYN+ACK, 3\&. send ACK) "
.ti -1c
.RI "void \fBtcp_socket_send_data\fP (int sock, \fB__u32\fP src_ip, \fB__u32\fP dest_ip, int src_port, int \fBdest_port\fP, char *data, int data_size, int seq, int ack, \fB__u16\fP window_size)"
.br
.RI "function: after tcp-connection, send data with ACK requesting "
.ti -1c
.RI "void \fBtcp_socket_send_data_no_ack\fP (int sock, \fB__u32\fP src_ip, \fB__u32\fP dest_ip, int src_port, int \fBdest_port\fP, char *data, int data_size, int seq, int ack, \fB__u16\fP window_size)"
.br
.RI "function: after tcp-connection, send data without ACK requesting "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBg_recv_flag\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct tcphdr prepare_empty_tcp (void)"

.PP
function: get empty tcphdr 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tchpdr 
.RE
.PP

.PP
Definition at line 7 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_get_checksum (struct iphdr ipv4h, struct tcphdr tcph, void * data, int datasize)"

.PP
function: tcphdr checksum value calculate with iphdr, data 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP iphdr ipv4h, struct tcphdr tcph, void *data, int datasize 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 81 of file make_tcp\&.c\&.
.SS "int tcp_make_connection (\fB__u32\fP src_ip, \fB__u32\fP dest_ip, int * src_port_copy, int dest_port, int * seq_copy, int * ack_copy, \fB__u16\fP window_size)"

.PP
function: make tcp connection (3-way handshake, 1\&. send SYN, 2\&. receive SYN+ACK, 3\&. send ACK) 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI__u32\fP src_ip, __u32 dest_ip, int *src_port_copy, int dest_port, int *seq_copy, int *ack_copy, __u16 window_size 
.RE
.PP
\fBReturns:\fP
.RS 4
int: socket 
.RE
.PP

.PP
Definition at line 110 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_ack_flag (struct tcphdr tcph)"

.PP
Definition at line 63 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_ack_seq (struct tcphdr tcph, \fB__u32\fP ack_seq)"

.PP
function: set tcphdr's ack sequence 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph, __u32 ack sequence 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 51 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_dest_port (struct tcphdr tcph, \fB__u16\fP dest_port)"

.PP
function: set tcphdr's src port 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph, __u16 src_port 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 39 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_psh_flag (struct tcphdr tcph)"

.PP
function: set tcphdr's psh flag as 1 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 69 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_seq (struct tcphdr tcph, \fB__u32\fP seq)"

.PP
Definition at line 45 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_src_port (struct tcphdr tcph, \fB__u16\fP src_port)"

.PP
function: set tcphdr's src port 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph, __u16 src_port 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 33 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_syn_flag (struct tcphdr tcph)"

.PP
function: set tcphdr's syn flag as 1 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 57 of file make_tcp\&.c\&.
.SS "struct tcphdr tcp_set_window_size (struct tcphdr tcph, \fB__u16\fP window_size)"

.PP
function: set tcphdr's window size 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIstruct\fP tcphdr tcph, __u16 window_size 
.RE
.PP
\fBReturns:\fP
.RS 4
struct tcphdr 
.RE
.PP

.PP
Definition at line 75 of file make_tcp\&.c\&.
.SS "void tcp_socket_send_data (int sock, \fB__u32\fP src_ip, \fB__u32\fP dest_ip, int src_port, int dest_port, char * data, int data_size, int seq, int ack, \fB__u16\fP window_size)"

.PP
function: after tcp-connection, send data with ACK requesting 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIint\fP sock, __u32 src_ip, __u32 dest_ip, int src_port, int dest_port, char *data, int data_size, int seq, int ack, __u16 window_size 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 220 of file make_tcp\&.c\&.
.SS "void tcp_socket_send_data_no_ack (int sock, \fB__u32\fP src_ip, \fB__u32\fP dest_ip, int src_port, int dest_port, char * data, int data_size, int seq, int ack, \fB__u16\fP window_size)"

.PP
function: after tcp-connection, send data without ACK requesting 
.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIint\fP sock, __u32 src_ip, __u32 dest_ip, int src_port, int dest_port, char *data, int data_size, int seq, int ack, __u16 window_size 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 280 of file make_tcp\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int g_recv_flag"

.PP
Definition at line 19 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
