.TH "srcs/base/make_ipv4.c" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/base/make_ipv4.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/make_ipv4\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct iphdr \fBprepare_empty_ipv4\fP (void)"
.br
.RI "function: get empty iphdr "
.ti -1c
.RI "struct iphdr \fBipv4_set_protocol\fP (struct iphdr ip_head, \fB__u8\fP protocol)"
.br
.RI "function: set iphdr's protocol "
.ti -1c
.RI "struct iphdr \fBipv4_set_saddr\fP (struct iphdr ip_head, \fB__u32\fP saddr)"
.br
.RI "function: set iphdr's src address "
.ti -1c
.RI "struct iphdr \fBipv4_set_daddr\fP (struct iphdr ip_head, \fB__u32\fP daddr)"
.br
.RI "function: set iphdr's dest address "
.ti -1c
.RI "struct iphdr \fBipv4_add_size\fP (struct iphdr ip_head, \fB__u32\fP data_size)"
.br
.RI "function: update iphdr's size(add data_size) "
.ti -1c
.RI "char * \fBpacket_assemble\fP (struct iphdr ip_head, void *data, \fB__u32\fP data_size)"
.br
.RI "function: assemble iphdr and data "
.ti -1c
.RI "int \fBmake_socket\fP (int protocol)"
.br
.RI "function: make ipv4 raw socket "
.ti -1c
.RI "void \fBsend_packet\fP (int sock, struct iphdr ip_head, char *packet, int port)"
.br
.RI "function: send packet to ip_head's dest address + port "
.ti -1c
.RI "\fB__u16\fP \fBin_cksum\fP (\fB__u16\fP *ptr, int nbytes)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fB__u16\fP in_cksum (\fB__u16\fP * ptr, int nbytes)"

.PP
Definition at line 92 of file make_ipv4\&.c\&.
.SS "struct iphdr ipv4_add_size (struct iphdr ip_head, \fB__u32\fP data_size)"

.PP
function: update iphdr's size(add data_size) 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstruct\fP iphdr ip_head, __u32 data_size 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 1 of file make_ipv4\&.c\&.
.SS "struct iphdr ipv4_set_daddr (struct iphdr ip_head, \fB__u32\fP daddr)"

.PP
function: set iphdr's dest address 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstruct\fP iphdr ip_head, __u32 daddr: dest address value 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 1 of file make_ipv4\&.c\&.
.SS "struct iphdr ipv4_set_protocol (struct iphdr ip_head, \fB__u8\fP protocol)"

.PP
function: set iphdr's protocol 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstruct\fP iphdr ip_head, __u8 protocol: protocol value 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 1 of file make_ipv4\&.c\&.
.SS "struct iphdr ipv4_set_saddr (struct iphdr ip_head, \fB__u32\fP saddr)"

.PP
function: set iphdr's src address 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstruct\fP iphdr ip_head, __u32 saddr: src address value 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 1 of file make_ipv4\&.c\&.
.SS "int make_socket (int protocol)"

.PP
function: make ipv4 raw socket 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIint\fP protocol 
.RE
.PP
\fBReturns\fP
.RS 4
int: socket 
.RE
.PP

.PP
Definition at line 60 of file make_ipv4\&.c\&.
.SS "char* packet_assemble (struct iphdr ip_head, void * data, \fB__u32\fP data_size)"

.PP
function: assemble iphdr and data 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstruct\fP iphdr ip_head, void *data, __u32 data_size 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 52 of file make_ipv4\&.c\&.
.SS "struct iphdr prepare_empty_ipv4 (void)"

.PP
function: get empty iphdr 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
struct iphdr 
.RE
.PP

.PP
Definition at line 1 of file make_ipv4\&.c\&.
.SS "void send_packet (int sock, struct iphdr ip_head, char * packet, int port)"

.PP
function: send packet to ip_head's dest address + port 
.PP
\fBDate\fP
.RS 4
2021/04/03 
.RE
.PP
\fBParameters\fP
.RS 4
\fIint\fP sock, struct iphdr ip_head: dest's iphdr, char *packet: packet for send, int port: dest port 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 77 of file make_ipv4\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
