.TH "MaskingArguments" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaskingArguments \- now values(ip, port) in subnet masking  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBsrc\fP [\fBIPV4_STRLEN\fP]"
.br
.ti -1c
.RI "unsigned char \fBdest\fP [\fBIPV4_STRLEN\fP]"
.br
.ti -1c
.RI "\fB__u32\fP \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
now values(ip, port) in subnet masking 


.PP
\fBDate\fP
.RS 4
2021/04/12 
.RE
.PP

.PP
Definition at line 64 of file header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char dest[\fBIPV4_STRLEN\fP]"
now source ipv4 string in subnet masking, format: XXX\&.XXX\&.XXX\&.XXX 
.PP
Definition at line 67 of file header\&.h\&.
.SS "\fB__u32\fP port"
now destination ipv4 string in subnet masking, format: XXX\&.XXX\&.XXX\&.XXX 
.PP
Definition at line 68 of file header\&.h\&.
.SS "unsigned char src[\fBIPV4_STRLEN\fP]"

.PP
Definition at line 66 of file header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
