.TH "md__r_e_a_d_m_e" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- network 
For Build -> make (Makefile)
.PP
For Run -> \&./attack\&.out (with root)
.PP
Simple Manual https://www.notion.so/DDoS-Util-Manual-9fe52082509d461387311222f2dce7e3 
