.TH "pcaprec_hdr" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcaprec_hdr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_replay\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__u32\fP \fBts_sec\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBts_usec\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBincl_len\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBorig_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file tcp_replay\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__u32\fP incl_len"

.PP
Definition at line 46 of file tcp_replay\&.h\&.
.SS "\fB__u32\fP orig_len"

.PP
Definition at line 47 of file tcp_replay\&.h\&.
.SS "\fB__u32\fP ts_sec"

.PP
Definition at line 44 of file tcp_replay\&.h\&.
.SS "\fB__u32\fP ts_usec"

.PP
Definition at line 45 of file tcp_replay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
