.TH "port_pair" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port_pair
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_replay\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__u8\fP \fBport1\fP"
.br
.ti -1c
.RI "\fB__u8\fP \fBport2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file tcp_replay\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__u8\fP port1"

.PP
Definition at line 9 of file tcp_replay\&.h\&.
.SS "\fB__u8\fP port2"

.PP
Definition at line 10 of file tcp_replay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
