.TH "session" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
session
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_replay\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBip_src\fP [16]"
.br
.ti -1c
.RI "char \fBip_dst\fP [16]"
.br
.ti -1c
.RI "\fB__u16\fP \fBsport\fP"
.br
.ti -1c
.RI "\fB__u16\fP \fBdport\fP"
.br
.ti -1c
.RI "\fB__u16\fP \fBmodify_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file tcp_replay\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__u16\fP dport"

.PP
Definition at line 17 of file tcp_replay\&.h\&.
.SS "char ip_dst[16]"

.PP
Definition at line 15 of file tcp_replay\&.h\&.
.SS "char ip_src[16]"

.PP
Definition at line 14 of file tcp_replay\&.h\&.
.SS "\fB__u16\fP modify_id"

.PP
Definition at line 20 of file tcp_replay\&.h\&.
.SS "\fB__u16\fP sport"

.PP
Definition at line 16 of file tcp_replay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
