.TH "sniff_ethernet" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sniff_ethernet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp_replay\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_char \fBether_dhost\fP [6]"
.br
.ti -1c
.RI "u_char \fBether_shost\fP [6]"
.br
.ti -1c
.RI "u_short \fBether_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file tcp_replay\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u_char ether_dhost[6]"

.PP
Definition at line 51 of file tcp_replay\&.h\&.
.SS "u_char ether_shost[6]"

.PP
Definition at line 52 of file tcp_replay\&.h\&.
.SS "u_short ether_type"

.PP
Definition at line 53 of file tcp_replay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
