.TH "tcp_pseudo_header" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_pseudo_header \- tcp pseudo header  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <make_tcp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__u32\fP \fBsource_address\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBdest_address\fP"
.br
.RI "src ipv4 address(__u32) "
.ti -1c
.RI "\fB__u8\fP \fBplaceholder\fP"
.br
.RI "dest ipv4 address(__u32) "
.ti -1c
.RI "\fB__u8\fP \fBprotocol\fP"
.br
.RI "placeholder (always 0) "
.ti -1c
.RI "\fB__u16\fP \fBtcp_length\fP"
.br
.RI "protocol (always IPPROTO_TCP) "
.in -1c
.SH "Detailed Description"
.PP 
tcp pseudo header 


.PP
\fBDate:\fP
.RS 4
2021/04/03 
.RE
.PP

.PP
Definition at line 13 of file make_tcp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__u32\fP dest_address"

.PP
src ipv4 address(__u32) 
.PP
Definition at line 15 of file make_tcp\&.h\&.
.SS "\fB__u8\fP placeholder"

.PP
dest ipv4 address(__u32) 
.PP
Definition at line 16 of file make_tcp\&.h\&.
.SS "\fB__u8\fP protocol"

.PP
placeholder (always 0) 
.PP
Definition at line 17 of file make_tcp\&.h\&.
.SS "\fB__u32\fP source_address"

.PP
Definition at line 14 of file make_tcp\&.h\&.
.SS "\fB__u16\fP tcp_length"

.PP
protocol (always IPPROTO_TCP) 
.PP
Definition at line 18 of file make_tcp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
