.TH "srcs/base/time_check.c" 3 "Tue Apr 13 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/base/time_check.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/time_check\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtime_check\fP (pthread_cond_t *cond_p, struct timespec *before_time_p, struct timespec *now_time_p, __u64 *produced_in_sec_p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void time_check (pthread_cond_t * cond_p, struct timespec * before_time_p, struct timespec * now_time_p, __u64 * produced_in_sec_p)"

.PP
Definition at line 4 of file time_check\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
