.TH "srcs/ddos/udp_flood.c" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/ddos/udp_flood.c
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'base/make_ipv4\&.h'\fP
.br
\fC#include 'base/subnet_mask\&.h'\fP
.br
\fC#include 'base/time_check\&.h'\fP
.br
\fC#include 'ddos/udp_flood\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATA\fP   'Hello, This is Data!'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBudp_flood_print_usage\fP (void)"
.br
.RI "print udp flooding usage "
.ti -1c
.RI "void * \fBgenerate_udp_flood\fP (void *data)"
.br
.RI "udp flooding generate thread "
.ti -1c
.RI "void * \fBudp_flood_time_check\fP (void *data)"
.br
.RI "udp flooding time check thread "
.ti -1c
.RI "void \fBudp_flood_main\fP (char *argv[])"
.br
.RI "udp flooding main function "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBg_num_threads\fP"
.br
.ti -1c
.RI "__u64 \fBg_udp_num_total\fP"
.br
.ti -1c
.RI "__u64 \fBg_udp_num_generated_in_sec\fP"
.br
.ti -1c
.RI "\fBInputArguments\fP \fBg_udp_input\fP"
.br
.ti -1c
.RI "\fB__u32\fP \fBg_udp_request_per_sec\fP"
.br
.ti -1c
.RI "\fBMaskingArguments\fP \fBg_udp_now\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBg_udp_mutex\fP = PTHREAD_MUTEX_INITIALIZER"
.br
.ti -1c
.RI "pthread_cond_t \fBg_udp_cond\fP = PTHREAD_COND_INITIALIZER"
.br
.ti -1c
.RI "struct timespec \fBg_udp_before_time\fP"
.br
.ti -1c
.RI "struct timespec \fBg_udp_now_time\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATA   'Hello, This is Data!'"

.PP
Definition at line 7 of file udp_flood\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void* generate_udp_flood (void * data)"

.PP
udp flooding generate thread 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 33 of file udp_flood\&.c\&.
.SS "void udp_flood_main (char * argv[])"

.PP
udp flooding main function 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 97 of file udp_flood\&.c\&.
.SS "void udp_flood_print_usage (void)"

.PP
print udp flooding usage 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file udp_flood\&.c\&.
.SS "void* udp_flood_time_check (void * data)"

.PP
udp flooding time check thread 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 83 of file udp_flood\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int g_num_threads"

.PP
Definition at line 20 of file main\&.c\&.
.SS "struct timespec g_udp_before_time"

.PP
Definition at line 23 of file udp_flood\&.c\&.
.SS "pthread_cond_t g_udp_cond = PTHREAD_COND_INITIALIZER"

.PP
Definition at line 21 of file udp_flood\&.c\&.
.SS "\fBInputArguments\fP g_udp_input"

.PP
Definition at line 15 of file udp_flood\&.c\&.
.SS "pthread_mutex_t g_udp_mutex = PTHREAD_MUTEX_INITIALIZER"

.PP
Definition at line 20 of file udp_flood\&.c\&.
.SS "\fBMaskingArguments\fP g_udp_now"

.PP
Definition at line 18 of file udp_flood\&.c\&.
.SS "struct timespec g_udp_now_time"

.PP
Definition at line 24 of file udp_flood\&.c\&.
.SS "__u64 g_udp_num_generated_in_sec"

.PP
Definition at line 13 of file udp_flood\&.c\&.
.SS "__u64 g_udp_num_total"

.PP
Definition at line 12 of file udp_flood\&.c\&.
.SS "\fB__u32\fP g_udp_request_per_sec"

.PP
Definition at line 16 of file udp_flood\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
