.TH "includes/ddos/udp_flood.h" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/ddos/udp_flood.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBudphdr\fP"
.br
.RI "udp header "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUDPHDR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBudp_flood_print_usage\fP (void)"
.br
.RI "print udp flooding usage "
.ti -1c
.RI "void * \fBgenerate_udp_flood\fP (void *data)"
.br
.RI "udp flooding generate thread "
.ti -1c
.RI "void * \fBudp_flood_time_check\fP (void *data)"
.br
.RI "udp flooding time check thread "
.ti -1c
.RI "void \fBudp_flood_main\fP (char *argv[])"
.br
.RI "udp flooding main function "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UDPHDR"

.PP
Definition at line 6 of file udp_flood\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void* generate_udp_flood (void * data)"

.PP
udp flooding generate thread 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 33 of file udp_flood\&.c\&.
.SS "void udp_flood_main (char * argv[])"

.PP
udp flooding main function 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIargv\fP arguments 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 97 of file udp_flood\&.c\&.
.SS "void udp_flood_print_usage (void)"

.PP
print udp flooding usage 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file udp_flood\&.c\&.
.SS "void* udp_flood_time_check (void * data)"

.PP
udp flooding time check thread 
.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP thread input, default: NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
void * 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINULL\fP always 
.RE
.PP

.PP
Definition at line 83 of file udp_flood\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
