.TH "udphdr" 3 "Thu Apr 15 2021" "Version v1.0" "ddos_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udphdr \- udp header  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <udp_flood\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_short \fBsrc_port\fP"
.br
.ti -1c
.RI "u_short \fBdest_port\fP"
.br
.ti -1c
.RI "u_short \fBlen\fP"
.br
.ti -1c
.RI "u_short \fBchecksum\fP"
.br
.ti -1c
.RI "char \fBdata\fP [1024]"
.br
.in -1c
.SH "Detailed Description"
.PP 
udp header 


.PP
\fBDate:\fP
.RS 4
2021/02/13 
.RE
.PP

.PP
Definition at line 11 of file udp_flood\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u_short checksum"
data length 
.PP
Definition at line 16 of file udp_flood\&.h\&.
.SS "char data[1024]"
checksum (0) 
.PP
Definition at line 17 of file udp_flood\&.h\&.
.SS "u_short dest_port"
source port (0) 
.PP
Definition at line 14 of file udp_flood\&.h\&.
.SS "u_short len"
destination port 
.PP
Definition at line 15 of file udp_flood\&.h\&.
.SS "u_short src_port"

.PP
Definition at line 13 of file udp_flood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ddos_util from the source code\&.
